### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by bensmithgb53** [CakesTwix/cloudstream-extensions-uk#31]
Please could you get this website on cloudstrram please? Could you add is so brings up all other website site videos that get posted on that website. Could you get other website link as spare links please with there websites name.

Here is the website https://soccerlive.app/

**Comment by CakesTwix** [comment]
@bensmithgb53, I do only for Ukrainian sites with Ukrainian content

**Comment by bensmithgb53** [comment]
> @bensmithgb53, I do only for Ukrainian sites with Ukrainian content

I see please I really want this site for cloudstream. I wish i knew how to code myself to make it but I don't. Please could you make this one UK one? Please

**Comment by CakesTwix** [comment]
No, it's principally just Ukrainian sites.
You don't know? Learn Kotlin. I didn't know it either and wanted to use CS3, instead of asking someone, I learned the language and made this repository

https://github.com/hexated/cloudstream-extensions-hexated
https://github.com/Blatzar/cloudstream-extensions
https://github.com/hexated/cloudstream-extensions-multilingual
